name: pytorch_study
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - anyio=2.2.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.0.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - cffi=1.14.6
  - charset-normalizer=2.0.4
  - colorama=0.4.4
  - cryptography=3.4.7
  - cudatoolkit=11.1.1
  - cycler=0.10.0
  - debugpy=1.4.1
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - fonttools=4.25.0
  - freetype=2.10.4
  - hdf5=1.10.4
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=3.2
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - intel-openmp=2021.3.0
  - ipykernel=6.2.0
  - ipython=7.27.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jinja2=3.0.1
  - jpeg=9d
  - json5=0.9.6
  - jsonschema=3.2.0
  - jupyter_client=7.0.1
  - jupyter_core=4.7.1
  - jupyter_server=1.4.1
  - jupyterlab=3.1.7
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.8.1
  - keras=2.6.0
  - kiwisolver=1.3.1
  - libopencv=4.0.1
  - libpng=1.6.37
  - libtiff=4.2.0
  - libuv=1.40.0
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.0.1
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - ninja=1.10.2
  - notebook=6.4.3
  - numexpr=2.7.3
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - opencv=4.0.1
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.2
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pickleshare=0.7.5
  - pip=21.2.2
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.17
  - py-opencv=4.0.1
  - pycparser=2.20
  - pygments=2.10.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.11
  - python-dateutil=2.8.2
  - pytorch=1.9.1
  - pytz=2021.1
  - pywin32=228
  - pywinpty=0.5.7
  - pyzmq=22.2.1
  - qt=5.9.7
  - requests=2.26.0
  - scipy=1.6.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sniffio=1.2.0
  - sqlite=3.36.0
  - terminado=0.9.4
  - testpath=0.5.0
  - tk=8.6.10
  - torchtext=0.10.1
  - torchvision=0.2.2
  - tornado=6.1
  - traitlets=5.0.5
  - typing_extensions=3.10.0.2
  - urllib3=1.26.6
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - xz=5.2.5
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==0.12.0
    - addict==2.4.0
    - aiohttp==3.7.4.post0
    - async-timeout==3.0.1
    - boto3==1.19.3
    - botocore==1.22.3
    - bz2file==0.98
    - cachetools==4.2.2
    - chardet==4.0.0
    - click==7.1.2
    - cloudpickle==2.0.0
    - dill==0.3.4
    - dopamine-rl==3.0.1
    - filelock==3.3.1
    - flask==2.0.2
    - fsspec==2021.8.1
    - future==0.18.2
    - gevent==21.8.0
    - gin-config==0.4.0
    - google-api-core==2.1.1
    - google-api-python-client==2.27.0
    - google-auth==1.35.0
    - google-auth-httplib2==0.1.0
    - google-auth-oauthlib==0.4.6
    - googleapis-common-protos==1.53.0
    - greenlet==1.1.2
    - grpcio==1.40.0
    - gunicorn==20.1.0
    - gym==0.21.0
    - h5py==3.5.0
    - httplib2==0.20.1
    - huggingface-hub==0.0.19
    - imageio==2.10.1
    - importlib-resources==5.3.0
    - itsdangerous==2.0.1
    - jmespath==0.10.0
    - joblib==1.0.1
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.4.1
    - jupyterthemes==0.20.0
    - kfac==0.2.0
    - lesscpy==0.15.0
    - lxml==4.6.3
    - markdown==3.3.4
    - mesh-tensorflow==0.1.19
    - model-index==0.1.11
    - mpmath==1.2.1
    - multidict==5.1.0
    - networkx==2.6.3
    - oauth2client==4.1.3
    - oauthlib==3.1.1
    - opencv-contrib-python==4.5.4.58
    - opencv-python==4.5.4.58
    - openmim==0.1.5
    - ordered-set==4.0.2
    - pillow==8.4.0
    - ply==3.11
    - prettytable==2.2.0
    - promise==2.3
    - protobuf==3.18.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.1
    - pypng==0.0.21
    - pytorch-lightning==1.4.8
    - pytorch-transformers==1.2.0
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - regex==2021.10.23
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - s3transfer==0.5.0
    - sacremoses==0.0.46
    - scikit-image==0.18.3
    - scikit-learn==0.24.2
    - sentencepiece==0.1.96
    - sklearn==0.0
    - sympy==1.9
    - tabulate==0.8.9
    - tensor2tensor==1.15.7
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow-addons==0.14.0
    - tensorflow-datasets==4.4.0
    - tensorflow-gan==2.1.0
    - tensorflow-hub==0.12.0
    - tensorflow-metadata==1.2.0
    - tensorflow-probability==0.7.0
    - termcolor==1.1.0
    - tf-slim==1.1.0
    - threadpoolctl==2.2.0
    - tifffile==2021.10.12
    - tokenizers==0.10.3
    - torch==1.8.0
    - torchkeras==2.1.2
    - torchmetrics==0.5.1
    - tqdm==4.62.3
    - transformers==4.11.3
    - typeguard==2.13.0
    - uritemplate==4.1.1
    - utils==1.0.1
    - werkzeug==2.0.1
    - yapf==0.31.0
    - yarl==1.6.3
    - zope-event==4.5.0
    - zope-interface==5.4.0
